### ISSUE TITLE
AbstractMethodError

### ISSUE THREAD

**Issue by legalimpurity** [thorbenprimke/realm-recyclerview#52]
Ok,so even your demo project is crashing with : 

```
                          Process: co.moonmonkeylabs.realmrecyclerview.example, PID: 24363
                                                                                         java.lang.AbstractMethodError: abstract method "void io.realm.RealmChangeListener.onChange(java.lang.Object)"
                                                                                             at io.realm.RealmResults.notifyChangeListeners(RealmResults.java:1032)
                                                                                             at io.realm.RealmResults.notifyChangeListeners(RealmResults.java:1018)
                                                                                             at io.realm.HandlerController.notifyRealmResultsCallbacks(HandlerController.java:296)
                                                                                             at io.realm.HandlerController.notifySyncRealmResultsCallbacks(HandlerController.java:277)
                                                                                             at io.realm.HandlerController.notifyTypeBasedListeners(HandlerController.java:268)
                                                                                             at io.realm.HandlerController.notifyAllListeners(HandlerController.java:255)
                                                                                             at io.realm.HandlerController.realmChanged(HandlerController.java:378)
                                                                                             at io.realm.HandlerController.handleMessage(HandlerController.java:110)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Are you guyz still maintaining this or what ?

**Comment by ohthejon** [comment]
Took me way too long to figure this out... 

Update your app's build.gradle to compile 'com.github.thorbenprimke:realm-recyclerview:0.9.16'

I was on 0.9.15

**Comment by thorbenprimke** [comment]
Oh. Sorry about that @ohthejon and @legalimpurity. I also upgraded the library now to Realm 1.0 and updated the readme with the new dependency. 

@legalimpurity - the repo was a bit behind with all the recent Realm change. Now that Realm is at 1.0, I'm going to fix anything that's broken. 

`compile 'com.github.thorbenprimke:realm-recyclerview:0.9.18'`
