### ISSUE TITLE
Enabling automaticUpdate causes NullPointerException

### ISSUE THREAD

**Issue by pingothedoer** [thorbenprimke/realm-recyclerview#67]
I have a fragment showing result of **RealmCourseItem** in a grid form. From that fragment , I am going to some other activity and add some more item in **RealmCourseItem**. After adding successfully, when I come back to my fragment , I am getting a `NullPointerException`.
This is the code in my Fragment (In my `onCreateView`) : 

```
        realm = Realm.getDefaultInstance();
        recyclerView = (RealmRecyclerView) view.findViewById(R.id.realm_recycler_view);
        realmResultList = realm.where(RealmCourseItem.class).findAll();
        adapter = new MyCoursesAdapter(getActivity(), realmResultList, true, true, mListener);
        recyclerView.setAdapter(adapter);
```

Here is the Exception :  

```
FATAL EXCEPTION: main
Process: pro.manager.attendance, PID: 20930
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
    at difflib.myers.MyersDiff.buildPath(MyersDiff.java:158)
    at difflib.myers.MyersDiff.diff(MyersDiff.java:98)
    at difflib.myers.MyersDiff.diff(MyersDiff.java:87)
    at difflib.DiffUtils.diff(DiffUtils.java:56)
    at difflib.DiffUtils.diff(DiffUtils.java:44)
    at io.realm.RealmBasedRecyclerViewAdapter$1.onChange(RealmBasedRecyclerViewAdapter.java:455)
    at io.realm.RealmBasedRecyclerViewAdapter$1.onChange(RealmBasedRecyclerViewAdapter.java:443)
    at io.realm.RealmResults.notifyChangeListeners(RealmResults.java:1016)
    at io.realm.HandlerController.notifyAllListeners(HandlerController.java:281)
    at io.realm.HandlerController.realmChanged(HandlerController.java:427)
    at io.realm.HandlerController.handleMessage(HandlerController.java:119)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6837)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by thorbenprimke** [comment]
@pingothedoer - thanks for the report. In order to re-produce and fix it, can you just clarify. 

This happens when you go from one fragment to another activity (and back) or does this happen when you go from one fragment to another fragment (and back)? 

On the second fragment/activity, you only add data, right? You don't remove any? Or does it modify an entry?

**Comment by abba-maker** [comment]
Hey guys.. Am having same NPE, updating my data in a service while displaying the list in a fragment. Really confused about this error

**Comment by abba-maker** [comment]
I think I found the reason for this error. It seems to happen if you try to update your data without providing the primaryKey. But it's kinda weird, the error isn't helpful. Anyway I hope this information is helpful @thorbenprimke 
Cheers

**Comment by mhd-adeeb-masoud** [comment]
Not sure if it was no-primary-key issue. It happens only on API 16, I solved it by turning off automatic updates and registering an onChange listener on my RealmResults calling RealmBasedRecyclerViewAdapter.updateRealmResults inside the listener.
